services:
  backend:
    build: .
    container_name: fastapi_backend
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - backend
      - redis
      - db
    env_file:
      - .env
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info

  celery_beat:
    build: .
    container_name: celery_beat
    restart: always
    depends_on:
      - backend
      - redis
      - db
      - celery_worker
    env_file:
      - .env
    command: celery -A app.core.celery_app.celery_app beat --loglevel=info

volumes:
  postgres_data:
