"""Add is_claim_prize to Winner

Revision ID: 278947729ab2
Revises: 4d56f9aae080
Create Date: 2025-02-13 00:20:25.570994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278947729ab2'
down_revision: Union[str, None] = '4d56f9aae080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('winners', sa.Column('is_claim_prize', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('winners', 'is_claim_prize')
    # ### end Alembic commands ###
