"""Add referral_token to InitialDelegator

Revision ID: 4a7f49069666
Revises: e9bd649333aa
Create Date: 2025-02-12 23:23:34.574096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7f49069666'
down_revision: Union[str, None] = 'e9bd649333aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initial_delegators', sa.Column('referral_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_initial_delegators_referral_token'), 'initial_delegators', ['referral_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_initial_delegators_referral_token'), table_name='initial_delegators')
    op.drop_column('initial_delegators', 'referral_token')
    # ### end Alembic commands ###
