"""Add is_participate to InitialDelegator

Revision ID: 721a52864607
Revises: 9a996b6b99a2
Create Date: 2025-02-09 14:21:32.750438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721a52864607'
down_revision: Union[str, None] = '9a996b6b99a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initial_delegators', sa.Column('is_participate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('initial_delegators', 'is_participate')
    # ### end Alembic commands ###
