"""Initial migration

Revision ID: 9a996b6b99a2
Revises: 
Create Date: 2025-02-05 12:40:36.283561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a996b6b99a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_delegators_id'), 'delegators', ['id'], unique=False)
    op.create_table('initial_delegators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_initial_delegators_id'), 'initial_delegators', ['id'], unique=False)
    op.create_table('lotteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winners_count', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotteries_id'), 'lotteries', ['id'], unique=False)
    op.create_table('winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('delegator_id', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['delegator_id'], ['delegators.id'], ),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_winners_id'), 'winners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_winners_id'), table_name='winners')
    op.drop_table('winners')
    op.drop_index(op.f('ix_lotteries_id'), table_name='lotteries')
    op.drop_table('lotteries')
    op.drop_index(op.f('ix_initial_delegators_id'), table_name='initial_delegators')
    op.drop_table('initial_delegators')
    op.drop_index(op.f('ix_delegators_id'), table_name='delegators')
    op.drop_table('delegators')
    # ### end Alembic commands ###
