"""Change winner relation

Revision ID: e9bd649333aa
Revises: d520af505cef
Create Date: 2025-02-09 19:53:43.024381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9bd649333aa'
down_revision: Union[str, None] = 'd520af505cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('winners', sa.Column('initial_delegator_id', sa.Integer(), nullable=False))
    op.drop_constraint('winners_delegator_id_fkey', 'winners', type_='foreignkey')
    op.create_foreign_key(None, 'winners', 'initial_delegators', ['initial_delegator_id'], ['id'])
    op.drop_column('winners', 'delegator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('winners', sa.Column('delegator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'winners', type_='foreignkey')
    op.create_foreign_key('winners_delegator_id_fkey', 'winners', 'delegators', ['delegator_id'], ['id'])
    op.drop_column('winners', 'initial_delegator_id')
    # ### end Alembic commands ###
